import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });
const TEMP_USER_ID = "00000000-0000-0000-0000-000000000000";

// Simple helper to create URL-friendly slugs
const slugify = (text: string) =>
  text.toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');

async function main() {
  await prisma.$transaction(async (tx) => {
    // 1. Setup Categories
    const categoryNames = ['Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Sides', 'Snacks', 'Sauces', 'Soups', 'Salads'];
    for (const name of categoryNames) {
      await tx.category.upsert({ where: { name }, update: {}, create: { name } });
    }
    const catMap = (await tx.category.findMany()).reduce((acc, c) => ({ ...acc, [c.name]: c.id }), {} as any);

    // 2. Setup Tags
    const tagsData = [
      { name: 'Dairy-Free', code: 'DF' },
      { name: 'Gluten-Free', code: 'GF' },
      { name: 'Low-Sodium', code: 'LS' },
      { name: 'Nut-Free', code: 'NF' },
      { name: 'Soy-Free', code: 'SF' },
      { name: 'Vegan', code: 'V' },
      { name: 'Vegetarian', code: 'VG' }
    ];

    const ingredientsToSeed = [
      // Staples
      { name: 'Salt', isStaple: true },
      { name: 'Baking Soda', isStaple: true },
      { name: 'Cinnamon', isStaple: true },
      { name: 'Granulated Sugar', isStaple: true },
      { name: 'Brown Sugar', isStaple: true },
      { name: 'All-Purpose Flour', isStaple: true },
      { name: 'Vanilla Extract', isStaple: true },
      { name: 'Garlic', isStaple: true },
      { name: 'Cumin', isStaple: true },
      { name: 'Oregeno', isStaple: true },

      // Fresh/Non-Staples
      { name: 'Eggs', isStaple: false },
      { name: 'Milk', isStaple: false },
      { name: 'Butter', isStaple: false },
      { name: 'Pasta', isStaple: false },
      { name: 'Tomato Sauce', isStaple: false },
      { name: 'Vegan Butter', isStaple: false },
      { name: 'Pumpkin Puree', isStaple: false },
      { name: 'Cream of Tartar', isStaple: false },
      { name: 'Pumpkin Pie Spice', isStaple: false },
      { name: 'Avocado Oil', isStaple: false },
      { name: 'Yellow Onion', isStaple: false },
      { name: 'Red Bell Pepper', isStaple: false },
      { name: 'Poblano Pepper', isStaple: false },
      { name: 'Cayenne Pepper', isStaple: false },
      { name: 'Cilantro', isStaple: false },
      { name: 'Diced Tomatoes', isStaple: false },
      { name: 'Vegetable Broth', isStaple: false },
      { name: 'Masa Harina', isStaple: false },
      { name: 'Lime Juice', isStaple: false },
      { name: 'Black Beans', isStaple: false },

    ];

    for (const t of tagsData) {
      await tx.tag.upsert({ where: { code: t.code }, update: { name: t.name }, create: t });
    }

    const tagMap = (await tx.tag.findMany()).reduce((acc, t) => ({ ...acc, [t.code]: t.id }), {} as any);

    console.log('🚀 Upserting Dev User...');

    await tx.user.upsert({
      where: { id: TEMP_USER_ID },
      update: {},
      create: {
        id: TEMP_USER_ID,
        email: "dev@example.com",
        password: "secure_dev_password"
      },
    });

    console.log('🌿 Syncing Ingredients...');
    const seededIngredients = await Promise.all(
      ingredientsToSeed.map(item =>
        tx.ingredient.upsert({
          where: { name: item.name },
          update: { isStaple: item.isStaple },
          create: { name: item.name, isStaple: item.isStaple }
        })
      )
    );

    // 2. Create the Map (Crucial Step)
    // This maps the string name (e.g., 'Salt') to the UUID generated by the DB
    const ingMap = seededIngredients.reduce((acc, ing) => {
      acc[ing.name] = ing.id;
      return acc;
    }, {} as Record<string, string>);

    console.log('👨‍🍳 Creating Recipes with Slugs...');

    const recipes = [
      {
        name: 'Scrambled Eggs',
        instructions: 'Whisk eggs and milk, cook in butter.',
        category: 'Breakfast',
        items: ['Eggs', 'Milk', 'Butter'],
        tags: []
      },
      {
        name: 'Pasta Marinara',
        instructions: 'Boil pasta, add sauce and garlic.',
        category: 'Dinner',
        items: ['Pasta', 'Tomato Sauce', 'Garlic'],
        tags: []
      },
      {
        name: 'Vegan Pumpkin Snickerdoodles',
        instructions: "In the bowl of a stand mixer with the paddle attachment or other large bowl with a handheld mixer, beat the vegan butter and sugars together until creamy, about 2 minutes.\nAdd the pumpkin puree and vanilla and mix until combined, scraping the sides and bottom of the bowl as needed.\nStop the mixer and add the flour. Sprinkle the cream of tartar, baking soda, salt, cinnamon and pumpkin pie spice on top of the flour. Turn the mixer on low speed and mix until just combined. Scrape the bottom and sides to make sure everything is well combined.\nCover the bowl and chill the cookie dough in the refrigerator for 1 hour. If you skip this step, the cookies won't be very chewy. So chill if you can!\nPreheat the oven to 350 degrees F and line two cookie sheets with parchment paper.\nTake about 1 1/2 tablespoons of dough and roll into a ball. Repeat, and roll all the balls in the cinnamon sugar topping. Place on baking sheets at least 2 inches apart and bake for 11-13 minutes. The cookies will be very soft, but firm up as they cool so be careful not to over bake. Let them cool for 10 minutes on the pan, then transfer to a cooling rack. Enjoy!",
        category: 'Dessert',
        items: ['Vegan Butter', 'Brown Sugar', 'Granulated Sugar', 'Pumpkin Puree', 'Vanilla Extract', 'All-Purpose Flour', 'Cream of Tartar', 'Baking Soda', 'Salt', 'Cinnamon', 'Pumpkin Pie Spice'],
        tags: ['V', 'VG', 'DF', 'NF', 'SF']
      },
      {
        name: 'Black Bean Stew',
        instructions: "Sauté: Warm the oil in a large pot or dutch oven over medium-high heat. Add the onion and bell peppers and sauté for 7 to 9 minutes, stirring occasionally, until the onion is beginning to brown. Reduce the heat to medium.\nAromatics: Add the garlic, finely diced cilantro stems, cumin, oregano, and cayenne pepper, if using. Mix well and sauté for 2 to 3 minutes, until the spices begin to stick to the bottom of the pot.\nSimmer: Add the black beans, tomatoes, and vegetable broth. Mix well and bring to a boil over high heat, then reduce the heat to medium and simmer for 20 minutes, stirring occasionally. If the soup begins to splatter, reduce the heat to medium-low, but maintain a simmer.\nThicken the Stew: Add the masa harina to a small bowl. Whisk 1/2 cup of warm water into the masa harina, add . Add the paste to the simmering soup and stir well. Simmer the soup for an additional 5 to 10 minutes, until it has thickened to your liking; stir frequently to prevent anything from sticking to the bottom of the pot. If the soup gets too thick, thin it out with water in 1/2 cup increments.\nFinal Touches: Turn the heat off and stir in the lime juice and 2 tablespoons of the chopped cilantro leaves. Add salt or additional seasonings to taste, as necessary.\nServe: Serve warm, topped with the remaining cilantro leaves. Store any leftovers in the refrigerator for up to to 5 days. You can also store this stew in the freezer for up to 2 months.",
        category: 'Dinner',
        items: ['Avocado Oil', 'Yellow Onion', 'Red Bell Pepper', 'Poblano Pepper', 'Cayenne Pepper', 'Cilantro', 'Diced Tomatoes', 'Vegetable Broth', 'Black Beans', 'Masa Harina', 'Lime Juice', 'Garlic', 'Cumin', 'Oregeno'],
        tags: ['GF', 'V', 'VG', 'DF', 'NF', 'SF']
      },
    ];

    for (const r of recipes) {
      const slug = slugify(r.name);

      // Determine the category ID dynamically from your catMap
      const categoryId = catMap[r.category] || catMap['Dinner'];

      await tx.recipe.upsert({
        where: { slug: slug },
        update: {
          instructions: r.instructions,
          categoryId: categoryId,
        },
        create: {
          name: r.name,
          slug: slug,
          instructions: r.instructions,
          authorId: TEMP_USER_ID,
          categoryId: categoryId,
          tags: {
            connect: r.tags.map(tagCode => {
              const tagId = tagMap[tagCode];
              if (!tagId) {
                throw new Error(`Tag "${tagCode}" not found in tagMap!`);
              }
              return { id: tagId };
            })
          },
          ingredients: {
            create: r.items.map(itemName => {
              const ingredientId = ingMap[itemName];
              if (!ingredientId) {
                throw new Error(`Ingredient "${itemName}" not found in ingMap. Check your ingredients seed list.`);
              }
              return {
                ingredientId: ingredientId,
                amount: "1 unit"
              };
            })
          }
        }
      });
    }


  });

  console.log('✨ Seeded successfully.');
}

main()
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
