import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { generateUniqueSlug } from '../src/utils/helperFunctions.js';
import { categoryNames, subCategories, tagsData } from './taxonomy.js';
import { ingredientsToSeed } from './ingredients.js';
import { recipes } from './recipes.js';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });
const TEMP_USER_ID = "00000000-0000-0000-0000-000000000000";

async function main() {
  await prisma.$transaction(async (tx) => {
    // Setup Categories
    console.log('📂 Syncing Categories...');

    for (const name of categoryNames) {
      await tx.category.upsert({ where: { name }, update: {}, create: { name } });
    }

    const catMap = (await tx.category.findMany()).reduce((acc, c) => ({ ...acc, [c.name]: c.id }), {} as any);

    console.log('📂 Syncing Subcategories...');

    const subCatMap: Record<string, string> = {};
    for (const sub of subCategories) {
        const created = await tx.subcategory.upsert({
            where: { name: sub.name },
            update: { categoryId: catMap[sub.parent] },
            create: { name: sub.name, categoryId: catMap[sub.parent] }
        });
        subCatMap[sub.name] = created.id;
    }
    
    // Setup Tags
    console.log('📂 Syncing Tags...');
    for (const t of tagsData) {
      await tx.tag.upsert({ where: { code: t.code }, update: { name: t.name }, create: t });
    }

    const tagMap = (await tx.tag.findMany()).reduce((acc, t) => ({ ...acc, [t.code]: t.id }), {} as any);

    console.log('🚀 Upserting Dev User...');

    await tx.user.upsert({
      where: { id: TEMP_USER_ID },
      update: {},
      create: {
        id: TEMP_USER_ID,
        email: "dev@example.com",
        password: "secure_dev_password"
      },
    });

    console.log('📏 Syncing Units...');
    const units = [
        { name: 'Cup', abbreviation: 'c' },
        { name: 'Teaspoon', abbreviation: 'tsp' },
        { name: 'Tablespoon', abbreviation: 'tbsp' },
        { name: 'Whole', abbreviation: 'unit' },
        { name: 'Gram', abbreviation: 'g' }
    ];
    const unitMap: Record<string, string> = {};
    for (const u of units) {
        const created = await tx.unit.upsert({
            where: { name: u.name },
            update: { abbreviation: u.abbreviation },
            create: u
        });
        unitMap[u.name] = created.id;
    }

    console.log('🌿 Syncing Ingredients...');
    const ingredientData = ingredientsToSeed();
    const seededIngredients = await Promise.all(
      ingredientData.map(item =>
        tx.ingredient.upsert({
          where: { name: item.name },
          update: { isStaple: item.isStaple },
          create: { name: item.name, isStaple: item.isStaple }
        })
      )
    );

    // 2. Create the Map (Crucial Step)
    // This maps the string name (e.g., 'Salt') to the UUID generated by the DB
    const ingMap = seededIngredients.reduce((acc, ing) => {
      acc[ing.name] = ing.id;
      return acc;
    }, {} as Record<string, string>);

    console.log('👨‍🍳 Creating Recipes with Slugs...');

    for (const r of recipes) {
      const slug = generateUniqueSlug(r.name);
      await tx.recipe.upsert({
        where: { slug },
        update: {},
        create: {
          name: r.name,
          slug,
          summary: r.summary,
          instructions: r.instructions,
          prepTime: r.prepTime,
          cookTime: r.cookTime,
          totalTime: (r.prepTime || 0) + (r.cookTime || 0),
          servings: r.servings,
          notes: r.notes,
          nutrition: r.nutrition,
          authorId: TEMP_USER_ID,
          categoryId: catMap[r.category],
          subcategoryId: subCatMap[r.subcategory],
          tags: {
            connect: r.tags.map(code => ({ id: tagMap[code] }))
          },
          ingredients: {
            create: r.items.map(item => ({
              amount: item.amount,
              ingredient: { connect: { id: ingMap[item.name] } },
              unit: { connect: { id: unitMap[item.unit] } }
            }))
          }
        }
      });
    }
  });

  console.log('✨ Seeded successfully.');
}

main()
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
