import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });
const TEMP_USER_ID = "00000000-0000-0000-0000-000000000000";

// Simple helper to create URL-friendly slugs
const slugify = (text: string) =>
  text.toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');

async function main() {
  await prisma.$transaction(async (tx) => {
    // 1. Setup Categories
    const categoryNames = [
      'Appetizers & Snacks',
      'Beverages',
      'Breakfast & Brunch',
      'Main Dishes',
      'Side Dishes',
      'Soups & Stews',
      'Desserts',
      'Breads',
      'Condiments & Sauces'
    ];

    const subCategories = [
      { name: 'Cookies', parent: 'Desserts' },
      { name: 'Pasta', parent: 'Main Dishes' },
      { name: 'Eggs', parent: 'Breakfast & Brunch' },
      { name: 'Stew', parent: 'Soups & Stews' }
    ];


    for (const name of categoryNames) {
      await tx.category.upsert({ where: { name }, update: {}, create: { name } });
    }
    const catMap = (await tx.category.findMany()).reduce((acc, c) => ({ ...acc, [c.name]: c.id }), {} as any);

    // 2. Setup Tags
    const tagsData = [
      { name: 'Dairy-Free', code: 'DF' },
      { name: 'Gluten-Free', code: 'GF' },
      { name: 'Low-Sodium', code: 'LS' },
      { name: 'Nut-Free', code: 'NF' },
      { name: 'Soy-Free', code: 'SF' },
      { name: 'Vegan', code: 'V' },
      { name: 'Vegetarian', code: 'VG' }
    ];

    const ingredientsToSeed = [
      // Staples
      { name: 'Salt', isStaple: true },
      { name: 'Baking Soda', isStaple: true },
      { name: 'Cinnamon', isStaple: true },
      { name: 'Granulated Sugar', isStaple: true },
      { name: 'Brown Sugar', isStaple: true },
      { name: 'All-Purpose Flour', isStaple: true },
      { name: 'Vanilla Extract', isStaple: true },
      { name: 'Garlic', isStaple: true },
      { name: 'Cumin', isStaple: true },
      { name: 'Oregeno', isStaple: true },

      // Fresh/Non-Staples
      { name: 'Eggs', isStaple: false },
      { name: 'Milk', isStaple: false },
      { name: 'Butter', isStaple: false },
      { name: 'Pasta', isStaple: false },
      { name: 'Tomato Sauce', isStaple: false },
      { name: 'Vegan Butter', isStaple: false },
      { name: 'Pumpkin Puree', isStaple: false },
      { name: 'Cream of Tartar', isStaple: false },
      { name: 'Pumpkin Pie Spice', isStaple: false },
      { name: 'Avocado Oil', isStaple: false },
      { name: 'Yellow Onion', isStaple: false },
      { name: 'Red Bell Pepper', isStaple: false },
      { name: 'Poblano Pepper', isStaple: false },
      { name: 'Cayenne Pepper', isStaple: false },
      { name: 'Cilantro', isStaple: false },
      { name: 'Diced Tomatoes', isStaple: false },
      { name: 'Vegetable Broth', isStaple: false },
      { name: 'Masa Harina', isStaple: false },
      { name: 'Lime Juice', isStaple: false },
      { name: 'Black Beans', isStaple: false }
    ];
    

    for (const t of tagsData) {
      await tx.tag.upsert({ where: { code: t.code }, update: { name: t.name }, create: t });
    }

    const tagMap = (await tx.tag.findMany()).reduce((acc, t) => ({ ...acc, [t.code]: t.id }), {} as any);

    console.log('🚀 Upserting Dev User...');

    await tx.user.upsert({
      where: { id: TEMP_USER_ID },
      update: {},
      create: {
        id: TEMP_USER_ID,
        email: "dev@example.com",
        password: "secure_dev_password"
      },
    });

    console.log('📏 Syncing Units...');
    const units = [
        { name: 'Cup', abbreviation: 'c' },
        { name: 'Teaspoon', abbreviation: 'tsp' },
        { name: 'Tablespoon', abbreviation: 'tbsp' },
        { name: 'Whole', abbreviation: 'unit' },
        { name: 'Gram', abbreviation: 'g' }
    ];
    const unitMap: Record<string, string> = {};
    for (const u of units) {
        const created = await tx.unit.upsert({
            where: { name: u.name },
            update: { abbreviation: u.abbreviation },
            create: u
        });
        unitMap[u.name] = created.id;
    }

    console.log('🌿 Syncing Ingredients...');
    const seededIngredients = await Promise.all(
      ingredientsToSeed.map(item =>
        tx.ingredient.upsert({
          where: { name: item.name },
          update: { isStaple: item.isStaple },
          create: { name: item.name, isStaple: item.isStaple }
        })
      )
    );

    // 2. Create the Map (Crucial Step)
    // This maps the string name (e.g., 'Salt') to the UUID generated by the DB
    const ingMap = seededIngredients.reduce((acc, ing) => {
      acc[ing.name] = ing.id;
      return acc;
    }, {} as Record<string, string>);

    console.log('📂 Syncing Subcategories...');

    const subCatMap: Record<string, string> = {};
    for (const sub of subCategories) {
        const created = await tx.subcategory.upsert({
            where: { name: sub.name },
            update: { categoryId: catMap[sub.parent] },
            create: { name: sub.name, categoryId: catMap[sub.parent] }
        });
        subCatMap[sub.name] = created.id;
    }

    console.log('👨‍🍳 Creating Recipes with Slugs...');

    const recipes = [
      {
        name: 'Scrambled Eggs',
        instructions: 'Whisk eggs and milk, cook in butter.',
        category: 'Breakfast & Brunch',
        subcategory: 'Eggs',
        items: [
          { name: 'Eggs', amount: 2, unit: 'Whole' },
          { name: 'Milk', amount: 0.25, unit: 'Cup' },
          { name: 'Butter', amount: 1, unit: 'Tablespoon' },
        ],
        tags: []
      },
      {
        name: 'Pasta Marinara',
        instructions: 'Boil pasta, add sauce and garlic.',
        category: 'Main Dishes',
        subcategory: 'Pasta',
        items: [
          { name: 'Pasta', amount: 1, unit: 'Cup' },
          { name: 'Tomato Sauce', amount: 0.5, unit: 'Cup' },
          { name: 'Garlic', amount: 1, unit: 'Whole' },
        ],
        tags: []
      },
      {
        name: 'Vegan Pumpkin Snickerdoodles',
        summary: 'Make these soft and thick Vegan Pumpkin Snickerdoodles for a fall treat! They’re easy to make in 1 bowl with real pumpkin, cream of tartar, and pumpkin pie spices, then rolled in cinnamon sugar for extra sweetness.',
        instructions: "In the bowl of a stand mixer with the paddle attachment or other large bowl with a handheld mixer, beat the vegan butter and sugars together until creamy, about 2 minutes.\nAdd the pumpkin puree and vanilla and mix until combined, scraping the sides and bottom of the bowl as needed.\nStop the mixer and add the flour. Sprinkle the cream of tartar, baking soda, salt, cinnamon and pumpkin pie spice on top of the flour. Turn the mixer on low speed and mix until just combined. Scrape the bottom and sides to make sure everything is well combined.\nCover the bowl and chill the cookie dough in the refrigerator for 1 hour. If you skip this step, the cookies won't be very chewy. So chill if you can!\nPreheat the oven to 350 degrees F and line two cookie sheets with parchment paper.\nTake about 1 1/2 tablespoons of dough and roll into a ball. Repeat, and roll all the balls in the cinnamon sugar topping. Place on baking sheets at least 2 inches apart and bake for 11-13 minutes. The cookies will be very soft, but firm up as they cool so be careful not to over bake. Let them cool for 10 minutes on the pan, then transfer to a cooling rack. Enjoy!",
        prepTime: 20,
        cookTime: 12,
        totalTime: 92,     
        servings: 18,
        category: 'Desserts',
        subcategory: 'Cookies',
        items: [
          { name: 'Vegan Butter', amount: 0.5, unit: 'Cup' },
          { name: 'Brown Sugar', amount: 0.5, unit: 'Cup' },
          { name: 'Granulated Sugar', amount: 0.5, unit: 'Cup' },
          { name: 'Pumpkin Puree', amount: 6, unit: 'Tablespoon' },
          { name: 'Vanilla Extract', amount: 2, unit: 'Teaspoon' },
          { name: 'All-Purpose Flour', amount: 1.75, unit: 'Cup' },
          { name: 'Cream of Tartar', amount: 1, unit: 'Teaspoon' },
          { name: 'Baking Soda', amount: 0.5, unit: 'Teaspoon' },
          { name: 'Salt', amount: 0.25, unit: 'Teaspoon' },
          { name: 'Cinnamon', amount: 1, unit: 'Teaspoon' },
          { name: 'Pumpkin Pie Spice', amount: 1, unit: 'Teaspoon' },
        ],
        tags: ['V', 'VG', 'DF', 'NF', 'SF'],
        nutrition: {
          "calories": 151,
          "carbohydrates": "24g",
          "protein": "1g",
          "fat": {
            "total": "4g",
            "saturated": "1g",
            "polyunsaturated": "1g",
            "monounsaturated": "2g"
          },
          "sodium": "106mg",
          "potassium": "63mg",
          "fiber": "1g",
          "sugar": "15g",
          "vitamins": {
            "vitaminA": "1019IU",
            "vitaminC": "0.2mg"
          },
          "minerals": {
            "calcium": "11mg",
            "iron": "1mg"
          }
        }
      },
      {
        name: 'Black Bean Stew',
        summary: 'This cozy Black Bean Stew is a Hispanic-inspired dish with bold flavors. Sautéed vegetables, canned black beans, Mexican herbs and spices, and masa harina are simmered in a thick and comforting vegetable broth.',
        instructions: "Sauté: Warm the oil in a large pot or dutch oven over medium-high heat. Add the onion and bell peppers and sauté for 7 to 9 minutes, stirring occasionally, until the onion is beginning to brown. Reduce the heat to medium.\nAromatics: Add the garlic, finely diced cilantro stems, cumin, oregano, and cayenne pepper, if using. Mix well and sauté for 2 to 3 minutes, until the spices begin to stick to the bottom of the pot.\nSimmer: Add the black beans, tomatoes, and vegetable broth. Mix well and bring to a boil over high heat, then reduce the heat to medium and simmer for 20 minutes, stirring occasionally. If the soup begins to splatter, reduce the heat to medium-low, but maintain a simmer.\nThicken the Stew: Add the masa harina to a small bowl. Whisk 1/2 cup of warm water into the masa harina, add . Add the paste to the simmering soup and stir well. Simmer the soup for an additional 5 to 10 minutes, until it has thickened to your liking; stir frequently to prevent anything from sticking to the bottom of the pot. If the soup gets too thick, thin it out with water in 1/2 cup increments.\nFinal Touches: Turn the heat off and stir in the lime juice and 2 tablespoons of the chopped cilantro leaves. Add salt or additional seasonings to taste, as necessary.\nServe: Serve warm, topped with the remaining cilantro leaves. Store any leftovers in the refrigerator for up to to 5 days. You can also store this stew in the freezer for up to 2 months.",
        prepTime: 10,
        cookTime: 50,
        totalTime: 60,     
        servings: 4,
        notes: 'Masa Harina Substitute: Masa harina adds a unique texture and flavor to this recipe, so I recommend using it if you can. However, if you do not have it, I’d recommend either (1) sprinkling 2 tablespoons of all purpose flour over the aromatics at the end of step 2, or (2) Mixing 1 tablespoons of cornstarch with 1/4 cup of water in step 4 in place of the masa paste – add this to the pot and stir well, and repeat one more time if the stew is still too thin for your liking.',
        category: 'Soups & Stews',
        subcategory: 'Stew',
        items: [
          { name: 'Avocado Oil', amount: 2, unit: 'Tablespoon' },
          { name: 'Yellow Onion', amount: 1, unit: 'Whole' },
          { name: 'Red Bell Pepper', amount: 1, unit: 'Whole' },
          { name: 'Poblano Pepper', amount: 1, unit: 'Whole' },
          { name: 'Garlic', amount: 1, unit: 'Cup' },
          { name: 'Cayenne Pepper', amount: 1, unit: 'Cup' },
          { name: 'Cilantro', amount: 1, unit: 'Cup' },
          { name: 'Diced Tomatoes', amount: 1, unit: 'Cup' },
          { name: 'Vegetable Broth', amount: 1, unit: 'Cup' },
          { name: 'Black Beans', amount: 1, unit: 'Cup' },
          { name: 'Masa Harina', amount: 1, unit: 'Cup' },
          { name: 'Lime Juice', amount: 1, unit: 'Cup' },
          { name: 'Cumin', amount: 1, unit: 'Cup' },
          { name: 'Oregeno', amount: 1, unit: 'Cup' },
        ],
        tags: ['GF', 'V', 'VG', 'DF', 'NF', 'SF'],
        nutrition: {
          "calories": 577,
          "carbohydrates": "96g",
          "protein": "32g",
          "fat": {
            "total": "10g",
            "saturated": "1g",
            "polyunsaturated": "2g",
            "monounsaturated": "5g"
          },
          "sodium": "19mg",
          "potassium": "1544mg",
          "fiber": "32g",
          "sugar": "7g",
          "vitamins": {
            "vitaminA": "1325IU",
            "vitaminC": "76mg"
          },
          "minerals": {
            "calcium": "163mg",
            "iron": "9mg"
          }
        }
      },
    ];

    for (const r of recipes) {
      const slug = slugify(r.name);
      await tx.recipe.upsert({
        where: { slug },
        update: {},
        create: {
          name: r.name,
          slug,
          summary: r.summary,
          instructions: r.instructions,
          prepTime: r.prepTime,
          cookTime: r.cookTime,
          totalTime: (r.prepTime || 0) + (r.cookTime || 0),
          servings: r.servings,
          notes: r.notes,
          nutrition: r.nutrition,
          authorId: TEMP_USER_ID,
          categoryId: catMap[r.category],
          subcategoryId: subCatMap[r.subcategory],
          tags: {
            connect: r.tags.map(code => ({ id: tagMap[code] }))
          },
          ingredients: {
            create: r.items.map(item => ({
              amount: item.amount,
              ingredient: { connect: { id: ingMap[item.name] } },
              unit: { connect: { id: unitMap[item.unit] } }
            }))
          }
        }
      });
    }
  });

  console.log('✨ Seeded successfully.');
}

main()
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
